### ISSUE TITLE
[Sign in form]: "email or username" input on mobile auto-capitalizes. It shouldn't.

### ISSUE THREAD

**Issue by carodew** [18F/usfwds#354] opened 2015-08-26 14:37 UTC
Steps to recreate: 

On a mobile device tap on the username field. The keyboard capitalization option changes to uppercase and the first letter (when typing) is capitalized. 

Since using an email address for sign-ins is preferred by most users, we think the soft keyboard for email should be triggered. However the field should not be invalid if someone enters a username that is not an email address. 

Video: https://drive.google.com/a/gsa.gov/file/d/0BzVTh-jwYUTHajI1UlA5dmtBUFU/view

Found on: 
Motorola Moto E, Android 4.4.4 Kitkat, Chrome 44
Apple iPhone 6, iOS 8.4, Safari
Samsung S5, Android 5 Lollipop, Chrome
Apple iPad 2, iOS 8.4, Safari

**Comment by msecret** [comment] 2015-08-28 17:33
Is this a duplicate of already closed issue: https://github.com/18F/usfwds/issues/367? @carodew

**Comment by carodew** [comment] 2015-08-28 20:40
It's the same behavior, but it's on the username/email field instead of the password field.

**Closed** 2015-08-31 15:34 UTC
Labels: bug, high
